services:
  backend:
    image: openjdk:21-jdk
    container_name: back
    volumes:
      - ./backend/target:/app
    working_dir: /app
    command: ["sh", "-c", "java -Dfile.encoding=UTF-8 -jar *.jar"]
    ports:
      - "8080:8080"
    environment:
      - LANG=th_TH.UTF-8
      - LANGUAGE=th_TH:th
      - LC_ALL=th_TH.UTF-8
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/integrateDatabase?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Bangkok
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - mysql
    networks:
      - Integrate_Network

  mysql:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: integrateDatabase
      LANG: th_TH.UTF-8
      LC_ALL: th_TH.UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - Integrate_Network

  frontend:
    image: nginx:latest
    container_name: front
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - Integrate_Network

volumes:
  mysql_data:

networks:
  Integrate_Network:
